-- MySQL Script generated by MySQL Workbench
-- Thu Feb 13 16:19:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_ex_softia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_ex_softia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_ex_softia` DEFAULT CHARACTER SET utf8 ;
USE `DB_ex_softia` ;

-- -----------------------------------------------------
-- Table `DB_ex_softia`.`Convention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_ex_softia`.`Convention` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(70) NOT NULL,
  `nbHeur` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_ex_softia`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_ex_softia`.`Etudiant` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `mail` VARCHAR(120) NOT NULL,
  `Convention_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `Convention_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Etudiant_Convention1_idx` (`Convention_id` ASC),
  CONSTRAINT `fk_Etudiant_Convention1`
    FOREIGN KEY (`Convention_id`)
    REFERENCES `DB_ex_softia`.`Convention` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_ex_softia`.`Attestation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_ex_softia`.`Attestation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Etudiant_id` INT UNSIGNED NOT NULL,
  `Convention_id` INT UNSIGNED NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`, `Etudiant_id`, `Convention_id`),
  INDEX `fk_Attestation_Etudiant_idx` (`Etudiant_id` ASC),
  INDEX `fk_Attestation_Convention1_idx` (`Convention_id` ASC),
  CONSTRAINT `fk_Attestation_Etudiant`
    FOREIGN KEY (`Etudiant_id`)
    REFERENCES `DB_ex_softia`.`Etudiant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attestation_Convention1`
    FOREIGN KEY (`Convention_id`)
    REFERENCES `DB_ex_softia`.`Convention` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
